all:
	g++ stm_1000000.cpp -std=c++11 -lpthread -o stm_1000000
	g++ stm_1000.cpp -std=c++11 -lpthread -o stm_1000
	g++ stm_1000000_disjoint.cpp -std=c++11 -lpthread -o stm_1000000_disjoint
	g++ stm_1000_disjoint.cpp -std=c++11 -lpthread -o stm_1000_disjoint

clean:
	rm stm_1000000
	rm stm_1000
	rm stm_1000000_disjoint
	rm stm_1000_disjoint
